### ISSUE TITLE
有id搜索不到，网站上是有的，例如SSNI–012

### ISSUE THREAD

**Issue by goodryb** [ovnrain/javbus-api#1]
![image](https://user-images.githubusercontent.com/3907975/199224908-1a00d0a5-57ef-462c-9992-83496206d84e.png)

**Comment by ovnrain** [comment]
<img width="544" alt="image" src="https://user-images.githubusercontent.com/18333709/199240651-495a2920-1466-419f-a904-337342340a13.png">

看起来并无问题，浏览器中访问 http://localhost:8892/api/v1/movies/ssni-012 试试呢

**Comment by goodryb** [comment]
@ovnrain 

现在又可以了，忽略吧
