### ISSUE TITLE
是否考虑支持添加代理功能

### ISSUE THREAD

**Issue by akynazh** [ovnrain/javbus-api#3]
国内用户访问不了javbus Q_Q

**Comment by ddpopbb3** [comment]
+1，非常需要这个功能，我现在docker启动，但是好像不走代理
` docker run -d \
    --name=javbus-api \
    --restart=unless-stopped \
    --network=host \
    -e HTTP_PROXY="http://192.168.31.221:7890" \
    -e HTTPS_PROXY="http://192.168.31.221:7890" \
    ovnrain/javbus-api`

**Comment by logiest617** [comment]
同样，不走系统代理，希望能支持添加代理功能

**Comment by ovnrain** [comment]
修改中，一会儿发布
